export const ADD_CABANA = "ADD_CABANA";
export const ADD_CABANA_SUCCESS = "ADD_CABANA_SUCCESS";
export const ADD_CABANA_ERROR = "ADD_CABANA_ERROR";

export const EDIT_CABANA = "EDIT_CABANA";
export const EDIT_CABANA_SUCCESS = "EDIT_CABANA_SUCCESS";
export const EDIT_CABANA_ERROR = "EDIT_CABANA_ERROR";

export const DELETE_CABANA = "DELETE_CABANA";
export const DELETE_CABANA_SUCCESS = "DELETE_CABANA_SUCCESS";
export const DELETE_CABANA_ERROR = "DELETE_CABANA_ERROR";

export const GET_CABANA = "GET_CABANA";
export const GET_CABANA_SUCCESS = "GET_CABANA_SUCCESS";
export const GET_CABANA_ERROR = "GET_CABANA_ERROR";

export const GET_CABANAS = "GET_CABANAS";
export const GET_CABANAS_SUCCESS = "GET_CABANAS_SUCCESS";
export const GET_CABANAS_ERROR = "GET_CABANAS_ERROR";

export const SET_CABANA = "SET_CABANA";